#!/usr/bin/env bash

echo "
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
" | kubectl apply -f -

brew upgrade kubernetes-helm
helm init --service-account tiller --tiller-namespace kube-system

helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install --name kubeapps --namespace kubeapps bitnami/kubeapps